vich_uploader:
  db_driver: orm

  mappings:
    pin_image:
      uri_prefix: /upload/pin
      upload_destination: "%kernel.project_dir%/public/upload/pin"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
